apiVersion: v1
kind: Template
metadata:
  name: noteapp
  annotations:
    description: infrastructure
objects:
# role binding (view pour le service account default: permettre d'effectuer les requetes rest concernant le deployment config)
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: view
  roleRef:
    name: view
  subjects:
  - kind: ServiceAccount
    name: default
# mongo write event store database (version ephemere)
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
    name: eventstore-database
  spec:
    ports:
    - name: mongo
      nodePort: 0
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: eventstore-database
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      app: eventstore-database
    name: eventstore-database
  spec:
    replicas: 1
    selector:
      name: eventstore-database
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: eventstore-database
      spec:
        containers:
        - capabilities: {}
          env:
          - name: MONGODB_USER
            value: devuser
          - name: MONGODB_PASSWORD
            value: devpassword
          - name: MONGODB_ADMIN_PASSWORD
            value: adminpassword
          - name: MONGODB_DATABASE
            value: eventstoredb
          image: centos/mongodb-36-centos7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            initialDelaySeconds: 3
            timeoutSeconds: 1
          resources:
            limits:
              memory: 256Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: "/dev/termination-log"
          volumeMounts:
          - mountPath: "/var/lib/mongodb/data"
            name: eventstore-database-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - emptyDir:
            medium: ''
          name: eventstore-database-data
# eventstore mongo rest api
- apiVersion: v1
  kind: Route
  metadata:
    name: eventstore-database-rest
  spec:
    port:
      targetPort: 3000
    to:
      kind: Service
      name: eventstore-database-rest
- kind: Service
  apiVersion: v1
  metadata:
    name: eventstore-database-rest
    labels:
      name: eventstore-database-rest
  spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
    selector:
      name: eventstore-database-rest
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
    name: eventstore-database-rest
    labels:
      name: eventstore-database-rest
  spec:
    replicas: 1
    selector:
      name: eventstore-database-rest
    triggers:
      - type: ConfigChange
    template:
      metadata:
        labels:
          name: eventstore-database-rest
      spec:
        initContainers:
        - name: wait-for-eventstore-database
          image: giantswarm/tiny-tools
          command: ["sh", "-c", "while `curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt --header \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" https://openshift.default.svc.cluster.local/oapi/v1/namespaces/$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)/deploymentconfigs/eventstore-database | jq \".status.availableReplicas == 0\"` ; do echo \"waiting for eventstore-database\"; sleep 2; done; exit 0;"]
        containers:
        - name: eventstore-database-rest
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: ME_CONFIG_DBSTRING
            value: mongodb://devuser:devpassword@eventstore-database.$(KUBERNETES_NAMESPACE).svc:27017/eventstoredb
          - name: ME_CONFIG_READONLY
            value: y
          image: linuxenko/mongo-rest
          ports:
          - containerPort: 3000
            protocol: TCP
# solr
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: solr
    name: solr
  spec:
    ports:
    - name: 8983-tcp
      port: 8983
      protocol: TCP
      targetPort: 8983
    selector:
      app: solr
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: solr
  spec:
    port:
      targetPort: 8983-tcp
    to:
      kind: Service
      name: solr
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: solr
    name: solr
  spec:
    replicas: 1
    selector:
      app: solr
    triggers:
      - type: ConfigChange
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
        post:
          failurePolicy: Retry
          execNewPod:
            containerName: tools
            env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            command: ["sh", "-c", "curl -X GET -G http://solr.$(KUBERNETES_NAMESPACE).svc:8983/solr/admin/cores -d action=CREATE -d name=mycores -d collection=my_collection -d configSet=_default"]
      type: Rolling
    template:
      metadata:
        labels:
          app: solr
      spec:
        containers:
        - image: giantswarm/tiny-tools
          name: tools
          command:
          - tail
          - '-f'
          - /dev/null
        - image: solr:7.4.0-alpine
          imagePullPolicy: Always
          name: solr
          ports:
          - containerPort: 8983
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 15
            periodSeconds: 20
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: "/opt/solr/server/solr/mycores"
            name: solr-data
          - mountPath: "/opt/solr/server/logs"
            name: solr-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir:
            medium: ''
          name: solr-data
        - emptyDir:
            medium: ''
          name: solr-log

